site_name: Tileio
site_dir: "site"
site_description: Tileio documentation
repo_name: AmbiqAI/tileio-docs
repo_url: https://github.com/AmbiqAI/tileio-docs
copyright: Copyright &copy; 2024 Ambiq

nav:
  - Home:
    - Home: index.md
    - Usage: usage/index.md
    - Demos: demos/index.md
    - Guides: guides/index.md
    - API: api/index.md

  - Usage:
    - usage/index.md
    - Dashboard: usage/dashboard.md
    - Tiles: usage/tiles.md

  - Demos:
    - demos/index.md
    - HeartKit Demo: demos/heartkit.md

  - Guides:
    - guides/index.md
    - New Dashboard: guides/new-dashboard.md
    - Demos: guides/demos.md

theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/logo.png
  icon:
      repo: fontawesome/brands/github-alt
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme)"
      primary: custom
      accent: blue
      toggle:
        icon: material/brightness-auto
        name: Use system theme
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to light theme
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to dark theme
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.path

    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.sections  # navigation.expand or navigation.sections
    - content.tabs.link # all code tabs change simultaneously


plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
          - https://docs.python.org/3/objects.inv
          - https://numpy.org/doc/stable/objects.inv
          options:
            docstring_style: google
            docstring_section_style: list
            heading_level: 3
            line_length: 120
            show_root_heading: true

extra_css:
  - css/mkdocstrings.css
  - css/termynal.css
  - css/custom.css

extra_javascript:
  - js/termynal.js
  - js/custom.js

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: 'docs/'
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - md_in_html
  - sane_lists
