# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026, Ambiq
"""MkDocs hook that copies the repository-root THIRD-PARTY-NOTICES.md into
docs/ before each build, so it ships as a page in the built site.

docs/third-party-notices.md is generated by this hook and is not meant to be
edited directly; the source of truth is THIRD-PARTY-NOTICES.md at the repo
root, produced by tools/gen_notices.py.
"""
from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_FILE = REPO_ROOT / "THIRD-PARTY-NOTICES.md"
TARGET_FILE = REPO_ROOT / "docs" / "third-party-notices.md"

FRONT_MATTER = "---\ntitle: Third-Party Notices\n---\n\n"


def on_pre_build(config, **kwargs):
    if not SOURCE_FILE.exists():
        raise FileNotFoundError(
            f"{SOURCE_FILE} not found; run "
            "`poetry run python tools/gen_notices.py` before building the site."
        )
    TARGET_FILE.write_text(FRONT_MATTER + SOURCE_FILE.read_text())
