# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026, Ambiq
"""Generate THIRD-PARTY-NOTICES.md from the locked Poetry environment.

The package set is read from ``poetry.lock`` (every direct and transitive
dependency needed to build the Tileio docs site). License metadata for each
package is pulled from ``pip-licenses``, which must be installed into the
active environment first, e.g.::

    poetry run pip install pip-licenses
    poetry run python tools/gen_notices.py

Installing pip-licenses can pull in a newer `wcwidth` than the one pinned in
poetry.lock (it's a transitive dependency of pip-licenses' own `prettytable`
dependency). If you need the environment to stay exactly on the lock after
generating notices, re-run ``poetry install --no-root --sync`` afterwards.

ADR-0005 (Tier 1) allows MIT, BSD, Apache-2.0, ISC, MPL-2.0 and PSF licensed
dependencies. Any license outside that list is recorded in the "Flagged"
section of the generated file. Copyleft (GPL/LGPL/AGPL family) or proprietary
licenses are treated as a hard failure: the script still writes the notices
file (so the finding is visible and auditable) but exits non-zero.

Run with ``--check`` in CI to fail on drift between the committed file and a
freshly generated one, in addition to the license-family checks above.
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LOCK_FILE = REPO_ROOT / "poetry.lock"
OUTPUT_FILE = REPO_ROOT / "THIRD-PARTY-NOTICES.md"

# ADR-0005 Tier 1 allow-list families.
ALLOWED_FAMILIES = {"mit", "bsd", "apache-2.0", "isc", "mpl-2.0", "psf"}

COPYLEFT_MARKERS = (
    "gpl",
    "gnu general public",
    "gnu lesser general public",
    "lgpl",
    "affero",
    "agpl",
)
PROPRIETARY_MARKERS = ("proprietary", "commercial", "other/proprietary")


def normalize_families(license_str: str) -> set[str]:
    """Map a pip-licenses free-text license string to canonical ADR-0005 families."""
    s = license_str.lower()
    families: set[str] = set()
    if "mit" in s:
        families.add("mit")
    if "bsd" in s:
        families.add("bsd")
    if "apache" in s:
        families.add("apache-2.0")
    if "isc" in s:
        families.add("isc")
    if "mozilla public license" in s or " mpl" in s or s.startswith("mpl"):
        families.add("mpl-2.0")
    if "python software foundation" in s or s.strip() == "psf":
        families.add("psf")
    return families


def classify(license_str: str) -> str:
    """Classify a license string as one of: allowed, copyleft, proprietary, other."""
    s = license_str.lower()
    if any(marker in s for marker in COPYLEFT_MARKERS):
        return "copyleft"
    if any(marker in s for marker in PROPRIETARY_MARKERS):
        return "proprietary"
    if normalize_families(license_str) & ALLOWED_FAMILIES:
        return "allowed"
    return "other"


def locked_package_names() -> list[str]:
    data = tomllib.loads(LOCK_FILE.read_text())
    return sorted({pkg["name"] for pkg in data["package"]}, key=str.lower)


def run_pip_licenses(package_names: list[str]) -> list[dict]:
    exe = shutil.which("pip-licenses")
    if exe is None:
        sys.exit(
            "pip-licenses is not installed in the active environment.\n"
            "Install it first, e.g.:\n"
            "  poetry run pip install pip-licenses\n"
            "  poetry run python tools/gen_notices.py\n"
        )
    cmd = [
        exe,
        "--format=json",
        "--with-urls",
        "--with-license-file",
        "--no-license-path",
        "--order=name",
        # pip-licenses excludes its own tooling dependencies (e.g. wcwidth,
        # prettytable) by default. --with-system re-includes them; the
        # --packages filter below still restricts output to what's actually
        # locked in poetry.lock, so pip-licenses' own tooling never leaks in.
        "--with-system",
        "--packages",
        *package_names,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, check=True)
    return json.loads(result.stdout)


def render(packages: list[dict]) -> str:
    packages = sorted(packages, key=lambda p: p["Name"].lower())

    flagged = [p for p in packages if classify(p["License"]) == "other"]
    copyleft = [p for p in packages if classify(p["License"]) == "copyleft"]
    proprietary = [p for p in packages if classify(p["License"]) == "proprietary"]

    lines: list[str] = []
    lines.append("# Third-Party Notices")
    lines.append("")
    lines.append(
        "This file is generated by `tools/gen_notices.py` from the locked "
        "Poetry environment (`poetry.lock`) used to build the Tileio "
        "documentation site. Do not edit by hand; re-run the generator "
        "instead. Tileio brand assets under `assets/` are Ambiq marks and "
        "are not third-party software; they are not listed here."
    )
    lines.append("")
    lines.append(
        f"ADR-0005 (Tier 1) allow-list: {', '.join(sorted(ALLOWED_FAMILIES))}. "
        f"{len(packages)} package(s) inventoried."
    )
    lines.append("")

    if copyleft or proprietary:
        lines.append(
            "> **BLOCKED:** one or more dependencies carry a copyleft or "
            "proprietary license. This is a licensing decision, not an "
            "automated one — see the Blocked section below before this "
            "file is treated as compliant."
        )
        lines.append("")

    lines.append("## Packages")
    lines.append("")
    lines.append("| Name | Version | License | URL |")
    lines.append("|------|---------|---------|-----|")
    for p in packages:
        url = p.get("URL") or "UNKNOWN"
        lines.append(f"| {p['Name']} | {p['Version']} | {p['License']} | {url} |")
    lines.append("")

    if copyleft or proprietary:
        lines.append("## Blocked (copyleft / proprietary)")
        lines.append("")
        for p in copyleft + proprietary:
            lines.append(f"- **{p['Name']} {p['Version']}** — {p['License']}")
        lines.append("")

    if flagged:
        lines.append("## Flagged (outside the ADR-0005 allow-list, not copyleft/proprietary)")
        lines.append("")
        for p in flagged:
            lines.append(f"- **{p['Name']} {p['Version']}** — {p['License']}")
        lines.append("")

    lines.append("## License texts")
    lines.append("")
    for p in packages:
        lines.append(f"### {p['Name']} {p['Version']} ({p['License']})")
        lines.append("")
        text = (p.get("LicenseText") or "").strip()
        if not text or text.upper() == "UNKNOWN":
            lines.append(
                f"License text not bundled with the package distribution; "
                f"see {p.get('URL') or 'the package index'} for the canonical text."
            )
        else:
            lines.append("```")
            lines.append(text)
            lines.append("```")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed file is out of date instead of writing it",
    )
    args = parser.parse_args()

    names = locked_package_names()
    packages = run_pip_licenses(names)

    found_names = {p["Name"].lower().replace("_", "-") for p in packages}
    locked_names = {n.lower().replace("_", "-") for n in names}
    missing = locked_names - found_names
    if missing:
        print(
            f"warning: {len(missing)} locked package(s) not found by pip-licenses "
            f"in the active environment (is it installed via `poetry install --no-root`?): "
            f"{', '.join(sorted(missing))}",
            file=sys.stderr,
        )

    content = render(packages)

    blocked = [p for p in packages if classify(p["License"]) in ("copyleft", "proprietary")]
    flagged = [p for p in packages if classify(p["License"]) == "other"]

    counts: dict[str, int] = {}
    for p in packages:
        family = classify(p["License"])
        counts[family] = counts.get(family, 0) + 1
    print(f"gen_notices: {len(packages)} package(s) — " + ", ".join(f"{k}={v}" for k, v in sorted(counts.items())))
    if flagged:
        print(f"gen_notices: flagged (outside allow-list): {[p['Name'] for p in flagged]}")
    if blocked:
        print(
            f"gen_notices: BLOCKED — copyleft/proprietary license(s) found: "
            f"{[(p['Name'], p['License']) for p in blocked]}",
            file=sys.stderr,
        )

    if args.check:
        if not OUTPUT_FILE.exists():
            print(f"gen_notices --check: {OUTPUT_FILE} does not exist", file=sys.stderr)
            return 1
        if OUTPUT_FILE.read_text() != content:
            print(f"gen_notices --check: {OUTPUT_FILE} is out of date; re-run without --check", file=sys.stderr)
            return 1
    else:
        OUTPUT_FILE.write_text(content)
        print(f"gen_notices: wrote {OUTPUT_FILE}")

    return 1 if blocked else 0


if __name__ == "__main__":
    raise SystemExit(main())
